services:
  aidiary-app:
    image: 376129842460.dkr.ecr.ap-northeast-2.amazonaws.com/aidiary-app:latest
    container_name: aidiary-app
    env_file:
      - .env.prod
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.mariadb.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MariaDBDialect
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    restart: unless-stopped
    volumes:
      - logs:/app/logs

  face-api:
    image: 376129842460.dkr.ecr.ap-northeast-2.amazonaws.com/face-api:latest
    container_name: face-api
    env_file:
      - .env.prod
    ports:
      - "5001:5001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    volumes:
      - hf_cache:/root/.cache/huggingface
      - generated_images:/app/generated_images

volumes:
  logs:
  hf_cache:
  generated_images:
