global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "aidiary-backend"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
